name: Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        # clipboard crate needs some libs on Linux
        run: sudo apt-get install xorg-dev libxcb-shape0-dev libxcb-xfixes0-dev

      - name: Install rustfmt
        run: rustup component add rustfmt

      - uses: actions/checkout@v2

      - name: Lint
        run: cargo fmt -- --check --verbose

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose

      - name: Show package list
        run: cargo package --list
