name: Publish

on:
  push:
    tags:
      - v*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        # clipboard crate needs some libs on Linux
        run: sudo apt-get install xorg-dev libxcb-shape0-dev libxcb-xfixes0-dev

      - uses: actions/checkout@v2

      - name: Publish
        run: cargo publish --token ${{ secrets.CARGO_TOKEN }}
